version: '3.8'

# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  ffc-ahwr-dashboard:
    build:
      target: development
    environment:
      NODE_ENV: test
    image: ffc-ahwr-dashboard-development
    container_name: ffc-ahwr-dashboard-test
    command: npm run test
    volumes:
      - ./test-output:/home/node/test-output
